<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>local.patch</groupId><artifactId>force-lte-ca-builder</artifactId><version>1</version>
  <dependencies>
    <dependency><groupId>org.smali</groupId><artifactId>baksmali</artifactId><version>2.3.4</version></dependency>
    <dependency><groupId>org.smali</groupId><artifactId>smali</artifactId><version>2.3.4</version></dependency>
  </dependencies>
</project>
