<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>local.patch</groupId><artifactId>force-lte-ca-builder</artifactId><version>1</version>
  <repositories>
    <repository><id>google-maven</id><url>https://dl.google.com/dl/android/maven2</url></repository>
  </repositories>
  <dependencies>
    <dependency><groupId>com.android.tools.smali</groupId><artifactId>smali-baksmali</artifactId><version>3.0.10</version></dependency>
    <dependency><groupId>com.android.tools.smali</groupId><artifactId>smali</artifactId><version>3.0.10</version></dependency>
  </dependencies>
</project>
